# Generated by Django 2.2.7 on 2020-04-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20200402_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='levels',
            new_name='stock_levels',
        ),
    ]
